pipeline:

  # build:
  #   image: node
  #   secrets: [ vault_pass ]
  #   commands:
  #     - npm i --loglevel silent
  #     - VAULT_PASS="$${VAULT_PASS}" ./vault/decrypt.sh
  #
  #     - npm run test-unitserver
  #     - DB_PATH=/tmp/db npm run test-integration
  #     - npm run test-unitclient
      # - npm run lint

  docker:
    image: plugins/docker
    storage_driver: vfs
    repo: omelhoro1/devshop-react-redux
    secrets: [ docker_username, docker_password ]
    when:
      branch: master

  deploy:
    image: drillster/drone-rsync
    user: captain
    hosts: [ "software-unchained.com" ]
    port: 22
    target: /tmp/devshop-react-redux-${DRONE_COMMIT}/
    include:
      - "docker-compose.yml"
    exclude:
      - "**.*"
    delete: false
    secrets: [ rsync_key ]
    script:
      - docker-compose -f /tmp/devshop-react-redux-${DRONE_COMMIT}/docker-compose.yml pull
      - docker-compose -f /tmp/devshop-react-redux-${DRONE_COMMIT}/docker-compose.yml -p devshop-react-redux up -d
    when:
      branch: master
