pipeline:
  docker:
    image: plugins/docker:latest
    storage_driver: vfs
    repo: omelhoro1/devshop
    secrets: [docker_username, docker_password]
    when:
      branch: master

  deploy:
    image: drillster/drone-rsync
    user: captain
    hosts: ["software-unchained.com"]
    port: 22
    target: /tmp/devshop-${DRONE_COMMIT}/
    include:
      - "docker-compose.yml"
    exclude:
      - "**.*"
    delete: false
    secrets: [rsync_key]
    script:
      - docker-compose -f /tmp/devshop-${DRONE_COMMIT}/docker-compose.yml pull
      - docker-compose -f /tmp/devshop-${DRONE_COMMIT}/docker-compose.yml -p devshop up -d
    when:
      branch: master
