version: "2"
services:
  devshop:
    image: omelhoro1/devshop
    container_name: devshop
    restart: unless-stopped
    env_file:
      - /home/captain/vault/secrets
    labels:
      - traefik.frontend.rule=Host:devshop.fischerops.com,devshop.software-unchained.com
      - traefik.enable=true
    volumes:
      - /tmp/db:/app/db
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
