version: '2'
services:

  devshop-vtex:
    image: omelhoro1/devshop-react-redux
    container_name: devshop-react-redux
    restart: unless-stopped
    env_file:
      - /home/captain/vault/secrets
    labels:
      - "traefik.frontend.rule=Host:devshop-react-redux.software-unchained.com"
    volumes:
      - /tmp/db:/app/db
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true
