version: '3'
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend/:/app

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    ports:
      - "10001:10001"
    volumes:
      - ./backend/:/app
      - ./backend/node_modules-docker:/app/node_modules
      - /tmp/db:/app/db
